# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TmdbTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TmdbTest
  pod 'Alamofire', '~> 5.0.0-beta.6'
  pod 'AlamofireObjectMapper', '~> 6.1.0'
  pod 'SideMenu', '~> 6.4.7'
  pod "TMDBSwift", '~> 0.5.1'

end
